"""
Test cases for Script Generating Action functionality.

This module contains unit tests for the ScriptGeneratingAction class
and its integration with the ManagerAgent.
"""

import unittest
import tempfile
import shutil
import os
from pathlib import Path
from unittest.mock import patch, MagicMock

from examples.alita_reproduction.actions.script_generating import ScriptGeneratingAction, ScriptMetadata
from examples.alita_reproduction.utils.code_quality import CodeQualityChecker, quick_check
from examples.alita_reproduction.agents.manager_agent import ManagerAgent


class TestScriptGeneratingAction(unittest.TestCase):
    """Test cases for ScriptGeneratingAction class."""
    
    def setUp(self):
        """Set up test fixtures before each test method."""
        # Create temporary directories for testing
        self.test_dir = tempfile.mkdtemp()
        self.templates_dir = os.path.join(self.test_dir, "templates")
        self.output_dir = os.path.join(self.test_dir, "output")
        
        os.makedirs(self.templates_dir, exist_ok=True)
        os.makedirs(self.output_dir, exist_ok=True)
        
        # Initialize the script generator with test directories
        self.script_generator = ScriptGeneratingAction(
            templates_dir=self.templates_dir,
            output_dir=self.output_dir
        )
        
        # Create a simple test template
        self.create_test_template()
    
    def tearDown(self):
        """Clean up after each test method."""
        # Remove temporary test directory
        shutil.rmtree(self.test_dir, ignore_errors=True)
    
    def create_test_template(self):
        """Create a simple test template for testing."""
        template_content = '''#!/usr/bin/env python3
"""
Test template for {{purpose}}

This is a test template.
"""

import logging

# Set up logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def main():
    """Main function for {{purpose}}."""
    name = "{{name}}"
    message = "{{message}}"
    
    print(f"Hello, {name}! {message}")
    logger.info(f"Test script executed for: {name}")


if __name__ == "__main__":
    main()
'''
        
        template_path = os.path.join(self.templates_dir, "test_template.py")
        with open(template_path, 'w', encoding='utf-8') as f:
            f.write(template_content)
    
    def test_initialization(self):
        """Test ScriptGeneratingAction initialization."""
        self.assertIsInstance(self.script_generator, ScriptGeneratingAction)
        self.assertTrue(os.path.exists(self.script_generator.templates_dir))
        self.assertTrue(os.path.exists(self.script_generator.output_dir))
        self.assertEqual(self.script_generator.default_author, "ALITA")
    
    def test_load_templates(self):
        """Test template loading functionality."""
        # Check if our test template was loaded
        templates = self.script_generator.get_available_templates()
        
        self.assertGreater(templates['total_templates'], 0)
        self.assertIn('test_template', templates['templates'])
        
        # Check template metadata
        test_template = templates['templates']['test_template']
        self.assertIn('description', test_template)
        self.assertIn('variables', test_template)
        self.assertIn('dependencies', test_template)
    
    def test_generate_script_from_template(self):
        """Test script generation from template."""
        requirements = {
            'purpose': 'testing script generation',
            'name': 'TestUser',
            'message': 'This is a test message',
            'description': 'Generated test script',
            'author': 'TestSuite'
        }
        
        result = self.script_generator.generate_script(
            template_name='test_template',
            script_name='test_generated_script',
            requirements=requirements
        )
        
        # Verify successful generation
        self.assertTrue(result['success'])
        self.assertIsNone(result['error'])
        self.assertTrue(os.path.exists(result['script_path']))
        
        # Verify content
        with open(result['script_path'], 'r', encoding='utf-8') as f:
            content = f.read()
        
        self.assertIn('testing script generation', content)
        self.assertIn('TestUser', content)
        self.assertIn('This is a test message', content)
        self.assertIn('Generated by: TestSuite', content)
    
    def test_generate_script_nonexistent_template(self):
        """Test script generation with non-existent template."""
        requirements = {'key': 'value'}
        
        result = self.script_generator.generate_script(
            template_name='nonexistent_template',
            script_name='test_script',
            requirements=requirements
        )
        
        # Verify failure
        self.assertFalse(result['success'])
        self.assertIsNotNone(result['error'])
        self.assertIn('not found', result['error'])
        self.assertIn('nonexistent_template', result['available_templates'])
    
    def test_create_script_from_requirements(self):
        """Test script creation from requirements without template."""
        result = self.script_generator.create_script_from_requirements(
            script_name='requirement_test_script',
            task_description='Process CSV data and generate reports',
            script_type='data_processing'
        )
        
        # Verify successful creation
        self.assertTrue(result['success'])
        self.assertIsNone(result['error'])
        self.assertTrue(os.path.exists(result['script_path']))
        
        # Verify content
        with open(result['script_path'], 'r', encoding='utf-8') as f:
            content = f.read()
        
        self.assertIn('Process CSV data and generate reports', content)
        self.assertIn('pandas as pd', content)
        self.assertIn('numpy as np', content)
        self.assertIn('def main():', content)
    
    def test_validate_script_syntax(self):
        """Test script syntax validation."""
        # Create a valid Python script
        valid_script_path = os.path.join(self.output_dir, 'valid_script.py')
        with open(valid_script_path, 'w', encoding='utf-8') as f:
            f.write('''#!/usr/bin/env python3
def main():
    print("Hello, world!")

if __name__ == "__main__":
    main()
''')
        
        result = self.script_generator.validate_script_syntax(valid_script_path)
        
        self.assertTrue(result['is_valid'])
        self.assertIsNone(result['error'])
        self.assertEqual(len(result['suggestions']), 0)
        
        # Create an invalid Python script
        invalid_script_path = os.path.join(self.output_dir, 'invalid_script.py')
        with open(invalid_script_path, 'w', encoding='utf-8') as f:
            f.write('''#!/usr/bin/env python3
def main()
    print("Hello, world!")  # Missing colon

if __name__ == "__main__":
    main()
''')
        
        result = self.script_generator.validate_script_syntax(invalid_script_path)
        
        self.assertFalse(result['is_valid'])
        self.assertIsNotNone(result['error'])
        self.assertGreater(len(result['suggestions']), 0)
    
    def test_script_metadata(self):
        """Test ScriptMetadata class functionality."""
        metadata = ScriptMetadata(
            name='test_script',
            description='Test script description'
        )
        
        self.assertEqual(metadata.name, 'test_script')
        self.assertEqual(metadata.description, 'Test script description')
        self.assertEqual(metadata.author, 'ALITA')
        self.assertIsNotNone(metadata.created_at)
        self.assertEqual(metadata.version, '1.0.0')
        self.assertEqual(metadata.dependencies, [])
        self.assertEqual(metadata.tags, [])


class TestCodeQualityChecker(unittest.TestCase):
    """Test cases for CodeQualityChecker class."""
    
    def setUp(self):
        """Set up test fixtures."""
        self.checker = CodeQualityChecker()
        self.test_dir = tempfile.mkdtemp()
    
    def tearDown(self):
        """Clean up after tests."""
        shutil.rmtree(self.test_dir, ignore_errors=True)
    
    def test_analyze_valid_code(self):
        """Test analysis of valid Python code."""
        valid_code = '''
import logging

def calculate_sum(a, b):
    """Calculate sum of two numbers."""
    return a + b

def main():
    """Main function."""
    result = calculate_sum(5, 3)
    logging.info(f"Result: {result}")

if __name__ == "__main__":
    main()
'''
        
        result = self.checker.analyze_code(valid_code)
        
        self.assertTrue(result['success'])
        self.assertTrue(result['syntax_valid'])
        self.assertGreaterEqual(result['overall_score'], 80)
        
    def test_analyze_invalid_syntax(self):
        """Test analysis of code with syntax errors."""
        invalid_code = '''
def broken_function(
    print("This has syntax errors")
'''
        
        result = self.checker.analyze_code(invalid_code)
        
        self.assertTrue(result['success'])  # Analysis succeeds even with syntax errors
        self.assertFalse(result['syntax_valid'])
        self.assertEqual(result['overall_score'], 0)  # Low score due to syntax error
    
    def test_analyze_security_risks(self):
        """Test detection of security risks."""
        risky_code = '''
import os

user_input = input("Enter command: ")
os.system(user_input)  # Security risk
eval(user_input)       # Another security risk
'''
        
        result = self.checker.analyze_code(risky_code)
        
        # Should detect security risks
        security_issues = [issue for issue in result['issues'] if issue.get('type') == 'security_risk']
        self.assertGreater(len(security_issues), 0)
        self.assertLess(result['overall_score'], 100)  # Score should be reduced
    
    def test_quick_check(self):
        """Test quick code quality check function."""
        code = '''
def simple_function():
    return "Hello, World!"
'''
        
        result = quick_check(code)
        
        self.assertIn('score', result)
        self.assertIn('syntax_valid', result)
        self.assertIn('total_issues', result)
        self.assertIn('has_security_risks', result)
        
        self.assertTrue(result['syntax_valid'])
        self.assertEqual(result['critical_issues'], 0)
        self.assertFalse(result['has_security_risks'])


class TestManagerAgentIntegration(unittest.TestCase):
    """Test cases for ManagerAgent integration with script generation."""
    
    def setUp(self):
        """Set up test fixtures."""
        # Create a mock LLM config to avoid API calls during testing
        mock_llm_config = MagicMock()
        
        with patch('examples.alita_reproduction.agents.manager_agent.OpenAILLMConfig', return_value=mock_llm_config):
            self.manager = ManagerAgent()
        
        # Create temporary directory for testing
        self.test_dir = tempfile.mkdtemp()
        
        # Override the script generator's output directory for testing
        self.manager.script_generator.output_dir = Path(self.test_dir)
    
    def tearDown(self):
        """Clean up after tests."""
        shutil.rmtree(self.test_dir, ignore_errors=True)
    
    def test_manager_initialization_with_script_generator(self):
        """Test that ManagerAgent initializes with script generation capability."""
        capabilities = self.manager.get_capabilities()
        
        self.assertIn('script_generation', capabilities)
        self.assertIn('template_management', capabilities)
        
        # Check that script generator is initialized
        self.assertIsNotNone(self.manager.script_generator)
        self.assertIsInstance(self.manager.script_generator, ScriptGeneratingAction)
    
    def test_assess_tool_needs_script_generation(self):
        """Test tool needs assessment for script generation tasks."""
        # Task that should trigger script generation
        task = "Create a script to process CSV data and generate reports"
        
        assessment = self.manager.assess_tool_needs(task)
        
        self.assertTrue(assessment['needs_additional_tools'])
        self.assertIn('script_generation', assessment['suggested_tools'])
    
    def test_create_script_from_requirements_via_manager(self):
        """Test script creation through ManagerAgent."""
        result = self.manager.create_script_from_requirements(
            script_name='manager_test_script',
            task_description='Test script creation through manager',
            script_type='automation'
        )
        
        self.assertTrue(result['success'])
        self.assertIsNone(result['error'])
        self.assertTrue(os.path.exists(result['script_path']))
    
    def test_get_available_templates_via_manager(self):
        """Test getting available templates through ManagerAgent."""
        result = self.manager.get_available_templates()
        
        self.assertIn('total_templates', result)
        self.assertIn('templates', result)
        self.assertIn('templates_directory', result)
    
    def test_validate_generated_script_via_manager(self):
        """Test script validation through ManagerAgent."""
        # First create a script
        create_result = self.manager.create_script_from_requirements(
            script_name='validation_test_script',
            task_description='Test script for validation',
            script_type='general'
        )
        
        self.assertTrue(create_result['success'])
        
        # Then validate it
        validation_result = self.manager.validate_generated_script(create_result['script_path'])
        
        self.assertTrue(validation_result['is_valid'])
        self.assertIsNone(validation_result['error'])
    
    def test_get_script_generation_status(self):
        """Test getting script generation status through ManagerAgent."""
        status = self.manager.get_script_generation_status()
        
        self.assertIn('available_templates', status)
        self.assertIn('templates_directory', status)
        self.assertIn('output_directory', status)
        self.assertIn('default_author', status)
        
        self.assertEqual(status['default_author'], 'ALITA')


class TestScriptGenerationWorkflow(unittest.TestCase):
    """Integration tests for complete script generation workflow."""
    
    def setUp(self):
        """Set up test fixtures."""
        self.test_dir = tempfile.mkdtemp()
        
        # Mock ManagerAgent to avoid API calls
        mock_llm_config = MagicMock()
        with patch('examples.alita_reproduction.agents.manager_agent.OpenAILLMConfig', return_value=mock_llm_config):
            self.manager = ManagerAgent()
            
        # Override directories for testing
        self.manager.script_generator.output_dir = Path(self.test_dir)
    
    def tearDown(self):
        """Clean up after tests."""
        shutil.rmtree(self.test_dir, ignore_errors=True)
    
    def test_complete_workflow_data_processing(self):
        """Test complete workflow for data processing script generation."""
        # Step 1: Create script
        create_result = self.manager.create_script_from_requirements(
            script_name='workflow_data_processor',
            task_description='Process sales data and generate monthly reports',
            script_type='data_processing',
            additional_requirements={
                'author': 'WorkflowTest',
                'tags': ['sales', 'reporting', 'monthly']
            }
        )
        
        self.assertTrue(create_result['success'])
        
        # Step 2: Validate script
        validation_result = self.manager.validate_generated_script(create_result['script_path'])
        self.assertTrue(validation_result['is_valid'])
        
        # Step 3: Check if script can be executed (syntax check)
        with open(create_result['script_path'], 'r', encoding='utf-8') as f:
            script_content = f.read()
        
        # Verify content contains expected elements
        self.assertIn('pandas as pd', script_content)
        self.assertIn('numpy as np', script_content)
        self.assertIn('sales data', script_content.lower())
        self.assertIn('monthly reports', script_content.lower())
        self.assertIn('Generated by: WorkflowTest', script_content)
    
    def test_complete_workflow_web_scraping(self):
        """Test complete workflow for web scraping script generation."""
        create_result = self.manager.create_script_from_requirements(
            script_name='workflow_web_scraper',
            task_description='Scrape product information from e-commerce websites',
            script_type='web_scraping'
        )
        
        self.assertTrue(create_result['success'])
        
        # Validate and check content
        validation_result = self.manager.validate_generated_script(create_result['script_path'])
        self.assertTrue(validation_result['is_valid'])
        
        with open(create_result['script_path'], 'r', encoding='utf-8') as f:
            script_content = f.read()
        
        # Verify web scraping specific content
        self.assertIn('requests', script_content)
        self.assertIn('BeautifulSoup', script_content)
        self.assertIn('product information', script_content.lower())


if __name__ == '__main__':
    # Set up logging for tests
    import logging
    logging.basicConfig(level=logging.WARNING)  # Reduce log noise during testing
    
    # Run all tests
    unittest.main(verbosity=2)