"""
ALITA MCP Server Implementation.

This module provides the ALITA-specific MCP server that hosts dynamically generated tools
and integrates with the EvoAgentX MCP ecosystem.
"""

import asyncio
import json
import logging
import os
import subprocess
import sys
from pathlib import Path
from typing import Dict, Any, List, Optional, Callable
from datetime import datetime
import uuid

# Set up logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class ALITAMCPServer:
    """
    ALITA-specific MCP server for hosting dynamically generated tools.
    
    This server manages Python scripts generated by ALITA and exposes them
    as MCP tools that can be discovered and called through the standard MCP protocol.
    """
    
    def __init__(
        self,
        server_name: str = "alita-tools",
        tools_dir: Optional[str] = None,
        persistence_file: Optional[str] = None,
        host: str = "localhost",
        port: int = 8765
    ):
        """
        Initialize the ALITA MCP server.
        
        Args:
            server_name: Name of the MCP server
            tools_dir: Directory containing generated tool scripts
            persistence_file: JSON file for tool metadata persistence
            host: Server host address
            port: Server port number
        """
        self.server_name = server_name
        self.host = host
        self.port = port
        
        # Set up directories
        self.base_dir = Path(__file__).parent.parent
        self.tools_dir = Path(tools_dir) if tools_dir else self.base_dir / "generated_scripts"
        self.persistence_file = Path(persistence_file) if persistence_file else self.base_dir / "mcp" / "tools_registry.json"
        
        # Ensure directories exist
        self.tools_dir.mkdir(exist_ok=True)
        self.persistence_file.parent.mkdir(exist_ok=True)
        
        # Tool registry
        self.tools_registry: Dict[str, Dict[str, Any]] = {}
        self.tool_functions: Dict[str, Callable] = {}
        
        # Server state
        self.server_process: Optional[subprocess.Popen] = None
        self.is_running = False
        
        # Load existing tools from persistence
        self._load_tools_registry()
        
        logger.info(f"ALITA MCP Server initialized: {server_name}")
        logger.info(f"Tools directory: {self.tools_dir}")
        logger.info(f"Persistence file: {self.persistence_file}")
    
    def _load_tools_registry(self) -> None:
        """Load tools registry from persistence file."""
        try:
            if self.persistence_file.exists():
                with open(self.persistence_file, 'r', encoding='utf-8') as f:
                    data = json.load(f)
                    self.tools_registry = data.get('tools', {})
                    logger.info(f"Loaded {len(self.tools_registry)} tools from registry")
            else:
                logger.info("No existing tools registry found, starting with empty registry")
        except Exception as e:
            logger.error(f"Error loading tools registry: {str(e)}")
            self.tools_registry = {}
    
    def _save_tools_registry(self) -> None:
        """Save tools registry to persistence file."""
        try:
            registry_data = {
                'server_name': self.server_name,
                'last_updated': datetime.now().isoformat(),
                'tools_count': len(self.tools_registry),
                'tools': self.tools_registry
            }
            
            with open(self.persistence_file, 'w', encoding='utf-8') as f:
                json.dump(registry_data, f, indent=2, ensure_ascii=False)
            
            logger.debug(f"Tools registry saved: {len(self.tools_registry)} tools")
        except Exception as e:
            logger.error(f"Error saving tools registry: {str(e)}")
    
    def register_script_as_tool(
        self,
        script_path: str,
        tool_name: str,
        description: str,
        parameters: Optional[Dict[str, Any]] = None,
        metadata: Optional[Dict[str, Any]] = None
    ) -> Dict[str, Any]:
        """
        Register a Python script as an MCP tool.
        
        Args:
            script_path: Path to the Python script
            tool_name: Name for the MCP tool
            description: Tool description
            parameters: Tool input parameters schema
            metadata: Additional tool metadata
            
        Returns:
            Registration result dictionary
        """
        logger.info(f"Registering script as MCP tool: {tool_name}")
        
        try:
            script_path = Path(script_path)
            if not script_path.exists():
                return {
                    "success": False,
                    "error": f"Script file not found: {script_path}",
                    "tool_name": tool_name
                }
            
            # Generate unique tool ID
            tool_id = str(uuid.uuid4())
            
            # Default parameters if not provided
            if parameters is None:
                parameters = {
                    "type": "object",
                    "properties": {
                        "input": {
                            "type": "string",
                            "description": "Input data for the script"
                        }
                    },
                    "required": []
                }
            
            # Create tool registry entry
            tool_info = {
                "id": tool_id,
                "name": tool_name,
                "description": description,
                "script_path": str(script_path.absolute()),
                "parameters": parameters,
                "metadata": metadata or {},
                "registered_at": datetime.now().isoformat(),
                "status": "active"
            }
            
            # Register in tools registry
            self.tools_registry[tool_name] = tool_info
            
            # Create executable function for the tool
            self.tool_functions[tool_name] = self._create_tool_function(tool_info)
            
            # Save registry
            self._save_tools_registry()
            
            logger.info(f"Tool registered successfully: {tool_name}")
            
            return {
                "success": True,
                "tool_id": tool_id,
                "tool_name": tool_name,
                "script_path": str(script_path),
                "error": None
            }
            
        except Exception as e:
            error_msg = f"Error registering script as tool: {str(e)}"
            logger.error(error_msg)
            return {
                "success": False,
                "error": error_msg,
                "tool_name": tool_name
            }
    
    def _create_tool_function(self, tool_info: Dict[str, Any]) -> Callable:
        """
        Create an executable function for an MCP tool.
        
        Args:
            tool_info: Tool information dictionary
            
        Returns:
            Callable function that executes the script
        """
        def tool_function(**kwargs) -> Dict[str, Any]:
            """Execute the registered Python script with given arguments."""
            script_path = tool_info["script_path"]
            tool_name = tool_info["name"]
            
            logger.info(f"Executing MCP tool: {tool_name}")
            logger.debug(f"Script path: {script_path}")
            logger.debug(f"Arguments: {kwargs}")
            
            try:
                # Prepare execution environment
                env = os.environ.copy()
                env["PYTHONPATH"] = str(Path(__file__).parent.parent.parent)
                
                # Create command to execute the script
                cmd = [sys.executable, script_path]
                
                # If there are keyword arguments, pass them as JSON through stdin
                input_data = None
                if kwargs:
                    input_data = json.dumps(kwargs).encode('utf-8')
                
                # Execute the script
                process = subprocess.run(
                    cmd,
                    input=input_data,
                    capture_output=True,
                    text=True,
                    env=env,
                    timeout=60  # 60 second timeout
                )
                
                if process.returncode == 0:
                    result = {
                        "success": True,
                        "output": process.stdout.strip(),
                        "error": None,
                        "tool_name": tool_name
                    }
                else:
                    result = {
                        "success": False,
                        "output": process.stdout.strip(),
                        "error": process.stderr.strip(),
                        "tool_name": tool_name,
                        "return_code": process.returncode
                    }
                
                logger.info(f"Tool execution completed: {tool_name}")
                return result
                
            except subprocess.TimeoutExpired:
                error_msg = f"Script execution timeout: {tool_name}"
                logger.error(error_msg)
                return {
                    "success": False,
                    "error": error_msg,
                    "tool_name": tool_name
                }
            except Exception as e:
                error_msg = f"Error executing tool {tool_name}: {str(e)}"
                logger.error(error_msg)
                return {
                    "success": False,
                    "error": error_msg,
                    "tool_name": tool_name
                }
        
        return tool_function
    
    def unregister_tool(self, tool_name: str) -> Dict[str, Any]:
        """
        Unregister an MCP tool.
        
        Args:
            tool_name: Name of the tool to unregister
            
        Returns:
            Unregistration result dictionary
        """
        logger.info(f"Unregistering MCP tool: {tool_name}")
        
        try:
            if tool_name not in self.tools_registry:
                return {
                    "success": False,
                    "error": f"Tool not found: {tool_name}",
                    "tool_name": tool_name
                }
            
            # Remove from registry and functions
            del self.tools_registry[tool_name]
            if tool_name in self.tool_functions:
                del self.tool_functions[tool_name]
            
            # Save registry
            self._save_tools_registry()
            
            logger.info(f"Tool unregistered successfully: {tool_name}")
            
            return {
                "success": True,
                "tool_name": tool_name,
                "error": None
            }
            
        except Exception as e:
            error_msg = f"Error unregistering tool: {str(e)}"
            logger.error(error_msg)
            return {
                "success": False,
                "error": error_msg,
                "tool_name": tool_name
            }
    
    def list_tools(self) -> Dict[str, Any]:
        """
        List all registered MCP tools.
        
        Returns:
            Dictionary containing tools information
        """
        logger.debug("Listing registered MCP tools")
        
        tools_info = {}
        for tool_name, tool_info in self.tools_registry.items():
            tools_info[tool_name] = {
                "id": tool_info["id"],
                "name": tool_info["name"],
                "description": tool_info["description"],
                "parameters": tool_info["parameters"],
                "registered_at": tool_info["registered_at"],
                "status": tool_info["status"],
                "metadata": tool_info.get("metadata", {})
            }
        
        return {
            "server_name": self.server_name,
            "tools_count": len(self.tools_registry),
            "tools": tools_info
        }
    
    def execute_tool(self, tool_name: str, **kwargs) -> Dict[str, Any]:
        """
        Execute an MCP tool by name.
        
        Args:
            tool_name: Name of the tool to execute
            **kwargs: Tool arguments
            
        Returns:
            Tool execution result
        """
        logger.info(f"Executing tool: {tool_name}")
        
        if tool_name not in self.tool_functions:
            return {
                "success": False,
                "error": f"Tool not found or not callable: {tool_name}",
                "available_tools": list(self.tools_registry.keys())
            }
        
        try:
            result = self.tool_functions[tool_name](**kwargs)
            return result
        except Exception as e:
            error_msg = f"Error executing tool {tool_name}: {str(e)}"
            logger.error(error_msg)
            return {
                "success": False,
                "error": error_msg,
                "tool_name": tool_name
            }
    
    def get_server_config(self) -> Dict[str, Any]:
        """
        Get MCP server configuration for use with EvoAgentX MCPToolkit.
        
        Returns:
            Server configuration dictionary
        """
        config = {
            "mcpServers": {
                self.server_name: {
                    "command": "python",
                    "args": [
                        "-c",
                        f"from {__name__} import ALITAMCPServer; "
                        f"server = ALITAMCPServer('{self.server_name}', "
                        f"'{self.tools_dir}', '{self.persistence_file}'); "
                        f"server.start_stdio_server()"
                    ],
                    "env": {
                        "PYTHONPATH": str(Path(__file__).parent.parent.parent)
                    }
                }
            }
        }
        
        return config
    
    def start_stdio_server(self):
        """Start the MCP server in stdio mode for integration with EvoAgentX."""
        import sys
        import json
        
        logger.info(f"Starting ALITA MCP server in stdio mode: {self.server_name}")
        
        try:
            # Simple stdio-based MCP protocol implementation
            while True:
                try:
                    line = sys.stdin.readline()
                    if not line:
                        break
                    
                    request = json.loads(line.strip())
                    method = request.get("method", "")
                    params = request.get("params", {})
                    request_id = request.get("id")
                    
                    if method == "tools/list":
                        # List available tools
                        tools_list = []
                        for tool_name, tool_info in self.tools_registry.items():
                            tools_list.append({
                                "name": tool_name,
                                "description": tool_info["description"],
                                "inputSchema": tool_info["parameters"]
                            })
                        
                        response = {
                            "jsonrpc": "2.0",
                            "id": request_id,
                            "result": {"tools": tools_list}
                        }
                        
                    elif method == "tools/call":
                        # Call a tool
                        tool_name = params.get("name", "")
                        arguments = params.get("arguments", {})
                        
                        result = self.execute_tool(tool_name, **arguments)
                        
                        response = {
                            "jsonrpc": "2.0",
                            "id": request_id,
                            "result": {"content": [{"type": "text", "text": json.dumps(result)}]}
                        }
                        
                    else:
                        # Unknown method
                        response = {
                            "jsonrpc": "2.0",
                            "id": request_id,
                            "error": {"code": -32601, "message": f"Method not found: {method}"}
                        }
                    
                    print(json.dumps(response), flush=True)
                    
                except json.JSONDecodeError:
                    continue
                except Exception as e:
                    logger.error(f"Error processing request: {str(e)}")
                    error_response = {
                        "jsonrpc": "2.0",
                        "id": request_id,
                        "error": {"code": -32603, "message": f"Internal error: {str(e)}"}
                    }
                    print(json.dumps(error_response), flush=True)
                    
        except KeyboardInterrupt:
            logger.info("ALITA MCP server stopped")
        except Exception as e:
            logger.error(f"ALITA MCP server error: {str(e)}")


def main():
    """Main entry point for the ALITA MCP server."""
    server = ALITAMCPServer()
    server.start_stdio_server()


if __name__ == "__main__":
    main()