"""
Script to MCP Tool Wrapper.

This module provides functionality to wrap Python scripts generated by ALITA
as standard MCP tools that can be discovered and called through the MCP protocol.
"""

import ast
import json
import logging
import re
import subprocess
import sys
from pathlib import Path
from typing import Dict, Any, List, Optional, Union
from dataclasses import dataclass
from datetime import datetime

# Set up logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


@dataclass
class MCPToolSpec:
    """Specification for an MCP tool."""
    name: str
    description: str
    parameters: Dict[str, Any]
    script_path: str
    metadata: Optional[Dict[str, Any]] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary representation."""
        return {
            "name": self.name,
            "description": self.description,
            "parameters": self.parameters,
            "script_path": self.script_path,
            "metadata": self.metadata or {}
        }


class ScriptToMCPWrapper:
    """
    Wrapper class that converts Python scripts to MCP tools.
    
    This class analyzes Python scripts and creates MCP tool specifications
    that can be registered with the ALITA MCP server.
    """
    
    def __init__(self, base_dir: Optional[str] = None):
        """
        Initialize the script wrapper.
        
        Args:
            base_dir: Base directory for script analysis
        """
        self.base_dir = Path(base_dir) if base_dir else Path(__file__).parent.parent
        self.analyzed_scripts: Dict[str, MCPToolSpec] = {}
        
        logger.info(f"ScriptToMCPWrapper initialized with base directory: {self.base_dir}")
    
    def analyze_script(self, script_path: str) -> Dict[str, Any]:
        """
        Analyze a Python script to extract MCP tool information.
        
        Args:
            script_path: Path to the Python script
            
        Returns:
            Analysis result dictionary
        """
        logger.info(f"Analyzing script: {script_path}")
        
        try:
            script_path = Path(script_path)
            if not script_path.exists():
                return {
                    "success": False,
                    "error": f"Script file not found: {script_path}"
                }
            
            with open(script_path, 'r', encoding='utf-8') as f:
                content = f.read()
            
            # Parse the script content
            tree = ast.parse(content)
            
            # Extract script information
            analysis_result = {
                "script_path": str(script_path.absolute()),
                "name": script_path.stem,
                "description": self._extract_description(tree, content),
                "functions": self._extract_functions(tree),
                "imports": self._extract_imports(tree),
                "parameters": self._infer_parameters(tree, content),
                "entry_point": self._find_entry_point(tree),
                "metadata": self._extract_metadata(content),
                "success": True,
                "error": None
            }
            
            logger.info(f"Script analysis completed: {script_path.name}")
            return analysis_result
            
        except SyntaxError as e:
            error_msg = f"Syntax error in script: {str(e)}"
            logger.error(error_msg)
            return {
                "success": False,
                "error": error_msg
            }
        except Exception as e:
            error_msg = f"Error analyzing script: {str(e)}"
            logger.error(error_msg)
            return {
                "success": False,
                "error": error_msg
            }
    
    def _extract_description(self, tree: ast.AST, content: str) -> str:
        """Extract description from script docstring or comments."""
        # Try to get module docstring
        docstring = ast.get_docstring(tree)
        if docstring:
            return docstring.split('\n')[0].strip()  # First line only
        
        # Try to extract from file header comments
        lines = content.split('\n')
        for line in lines[:10]:  # Check first 10 lines
            if line.strip().startswith('"""') and line.strip().endswith('"""'):
                return line.strip().strip('"""').strip()
            elif line.strip().startswith('#') and 'description' in line.lower():
                return line.strip('#').strip()
        
        return "Generated script (no description available)"
    
    def _extract_functions(self, tree: ast.AST) -> List[Dict[str, Any]]:
        """Extract function definitions from the script."""
        functions = []
        
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef):
                func_info = {
                    "name": node.name,
                    "args": [arg.arg for arg in node.args.args],
                    "docstring": ast.get_docstring(node) or "",
                    "line_number": node.lineno
                }
                functions.append(func_info)
        
        return functions
    
    def _extract_imports(self, tree: ast.AST) -> List[str]:
        """Extract import statements from the script."""
        imports = []
        
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    imports.append(alias.name)
            elif isinstance(node, ast.ImportFrom):
                if node.module:
                    imports.append(node.module)
        
        return imports
    
    def _infer_parameters(self, tree: ast.AST, content: str) -> Dict[str, Any]:
        """
        Infer MCP tool parameters from script analysis.
        
        This tries to intelligently determine what parameters the script expects.
        """
        # Default parameters schema
        parameters = {
            "type": "object",
            "properties": {},
            "required": []
        }
        
        # Look for main function parameters
        main_function = None
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef) and node.name == "main":
                main_function = node
                break
        
        if main_function:
            # Extract parameters from main function
            for arg in main_function.args.args:
                if arg.arg != "self":  # Skip self parameter
                    param_info = {
                        "type": "string",  # Default to string
                        "description": f"Parameter: {arg.arg}"
                    }
                    parameters["properties"][arg.arg] = param_info
        else:
            # Look for command line argument parsing
            if "argparse" in content:
                # Try to extract argparse definitions
                arg_patterns = [
                    r"add_argument\(\s*['\"]--?(\w+)['\"].*?help\s*=\s*['\"]([^'\"]+)['\"]",
                    r"add_argument\(\s*['\"]--?(\w+)['\"]"
                ]
                
                for pattern in arg_patterns:
                    matches = re.findall(pattern, content, re.MULTILINE | re.DOTALL)
                    for match in matches:
                        if len(match) == 2:
                            arg_name, help_text = match
                            param_info = {
                                "type": "string",
                                "description": help_text
                            }
                        else:
                            arg_name = match[0] if isinstance(match, tuple) else match
                            param_info = {
                                "type": "string",
                                "description": f"Command line argument: {arg_name}"
                            }
                        
                        parameters["properties"][arg_name] = param_info
            
            # If no specific parameters found, add a generic input parameter
            if not parameters["properties"]:
                parameters["properties"]["input"] = {
                    "type": "string",
                    "description": "Input data for the script"
                }
        
        return parameters
    
    def _find_entry_point(self, tree: ast.AST) -> Optional[str]:
        """Find the script entry point (main function or __main__ block)."""
        has_main_function = False
        has_main_block = False
        
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef) and node.name == "main":
                has_main_function = True
            elif isinstance(node, ast.If):
                # Check for if __name__ == "__main__":
                if (isinstance(node.test, ast.Compare) and
                    isinstance(node.test.left, ast.Name) and
                    node.test.left.id == "__name__"):
                    has_main_block = True
        
        if has_main_function and has_main_block:
            return "main"
        elif has_main_block:
            return "__main__"
        else:
            return "direct"
    
    def _extract_metadata(self, content: str) -> Dict[str, Any]:
        """Extract additional metadata from script content."""
        metadata = {
            "has_argparse": "argparse" in content,
            "has_logging": "logging" in content,
            "has_json": "import json" in content,
            "line_count": len(content.split('\n')),
            "estimated_complexity": "simple"  # Could be enhanced with more analysis
        }
        
        # Estimate complexity based on various factors
        complexity_indicators = [
            "class " in content,
            "async def" in content,
            "threading" in content,
            "multiprocessing" in content,
            len(re.findall(r"def \w+", content)) > 5,
            len(content.split('\n')) > 100
        ]
        
        if sum(complexity_indicators) >= 3:
            metadata["estimated_complexity"] = "complex"
        elif sum(complexity_indicators) >= 1:
            metadata["estimated_complexity"] = "moderate"
        
        return metadata
    
    def wrap_script(
        self,
        script_path: str,
        tool_name: Optional[str] = None,
        tool_description: Optional[str] = None,
        custom_parameters: Optional[Dict[str, Any]] = None
    ) -> MCPToolSpec:
        """
        Wrap a script as an MCP tool specification.
        
        Args:
            script_path: Path to the Python script
            tool_name: Custom tool name (defaults to script name)
            tool_description: Custom tool description
            custom_parameters: Custom parameters schema
            
        Returns:
            MCPToolSpec object
        """
        logger.info(f"Wrapping script as MCP tool: {script_path}")
        
        # Analyze the script
        analysis = self.analyze_script(script_path)
        
        if not analysis["success"]:
            raise ValueError(f"Failed to analyze script: {analysis['error']}")
        
        # Create tool specification
        tool_spec = MCPToolSpec(
            name=tool_name or analysis["name"],
            description=tool_description or analysis["description"],
            parameters=custom_parameters or analysis["parameters"],
            script_path=analysis["script_path"],
            metadata={
                "analysis": analysis,
                "wrapped_at": datetime.now().isoformat(),
                "entry_point": analysis["entry_point"],
                "functions": analysis["functions"],
                "imports": analysis["imports"]
            }
        )
        
        # Store the wrapped script
        self.analyzed_scripts[tool_spec.name] = tool_spec
        
        logger.info(f"Script wrapped successfully as tool: {tool_spec.name}")
        return tool_spec
    
    def create_mcp_tool_config(self, tool_spec: MCPToolSpec) -> Dict[str, Any]:
        """
        Create MCP tool configuration for integration with ALITA MCP server.
        
        Args:
            tool_spec: MCP tool specification
            
        Returns:
            MCP tool configuration dictionary
        """
        config = {
            "name": tool_spec.name,
            "description": tool_spec.description,
            "inputSchema": tool_spec.parameters,
            "script_path": tool_spec.script_path,
            "metadata": tool_spec.metadata
        }
        
        return config
    
    def wrap_directory(
        self,
        directory: str,
        pattern: str = "*.py",
        exclude_patterns: Optional[List[str]] = None
    ) -> List[MCPToolSpec]:
        """
        Wrap all Python scripts in a directory as MCP tools.
        
        Args:
            directory: Directory containing Python scripts
            pattern: File pattern to match (default: *.py)
            exclude_patterns: Patterns to exclude
            
        Returns:
            List of MCPToolSpec objects
        """
        logger.info(f"Wrapping scripts in directory: {directory}")
        
        directory = Path(directory)
        if not directory.exists():
            raise ValueError(f"Directory not found: {directory}")
        
        exclude_patterns = exclude_patterns or ["__*", "test_*", "*_test.py"]
        tool_specs = []
        
        for script_file in directory.glob(pattern):
            # Check if file should be excluded
            should_exclude = False
            for exclude_pattern in exclude_patterns:
                if script_file.match(exclude_pattern):
                    should_exclude = True
                    break
            
            if should_exclude:
                logger.debug(f"Excluding script: {script_file.name}")
                continue
            
            try:
                tool_spec = self.wrap_script(str(script_file))
                tool_specs.append(tool_spec)
            except Exception as e:
                logger.warning(f"Failed to wrap script {script_file.name}: {str(e)}")
        
        logger.info(f"Wrapped {len(tool_specs)} scripts from directory")
        return tool_specs
    
    def test_script_execution(self, script_path: str, test_args: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """
        Test script execution to validate it works as an MCP tool.
        
        Args:
            script_path: Path to the Python script
            test_args: Test arguments to pass to the script
            
        Returns:
            Test execution result
        """
        logger.info(f"Testing script execution: {script_path}")
        
        try:
            script_path = Path(script_path)
            if not script_path.exists():
                return {
                    "success": False,
                    "error": f"Script file not found: {script_path}"
                }
            
            # Prepare test command
            cmd = [sys.executable, str(script_path)]
            
            # Prepare input data if provided
            input_data = None
            if test_args:
                input_data = json.dumps(test_args).encode('utf-8')
            
            # Execute the script
            process = subprocess.run(
                cmd,
                input=input_data,
                capture_output=True,
                text=True,
                timeout=30  # 30 second timeout for testing
            )
            
            result = {
                "success": process.returncode == 0,
                "stdout": process.stdout.strip(),
                "stderr": process.stderr.strip(),
                "return_code": process.returncode,
                "script_path": str(script_path)
            }
            
            if result["success"]:
                logger.info(f"Script test passed: {script_path.name}")
            else:
                logger.warning(f"Script test failed: {script_path.name}")
            
            return result
            
        except subprocess.TimeoutExpired:
            return {
                "success": False,
                "error": "Script execution timeout during test",
                "script_path": str(script_path)
            }
        except Exception as e:
            return {
                "success": False,
                "error": f"Error testing script: {str(e)}",
                "script_path": str(script_path)
            }